### ISSUE TITLE
Need to "initialize" build panel before building

### ISSUE THREAD

**Issue by razor85** [KrzysztofBuchacz/ParallelBuildsMonitor#51]
If I just start the building and Parallels Build Monitor window is hidden (docked), it will not work. I need to go there, show the window and then start the build process. It is no trouble at all, but when I start compiling a huge project and notice this, it's troublesome to stop the build, open the window (initialize) and then build again.

**Comment by KrzysztofBuchacz** [comment]
Thanks for feedback . This problem is fixed in version 1.8, which is in beta tests.

**Comment by razor85** [comment]
Thanks! Nice to hear, keep up the good work! This extension is really awesome :)

**Comment by KrzysztofBuchacz** [comment]
Closing as fixed

**Comment by razor85** [comment]
Thanks!
