### ISSUE TITLE
Extension is not loaded in VS 2019.1 due to unsupported asynchronous loading

### ISSUE THREAD

**Issue by ArchiDevil** [KrzysztofBuchacz/ParallelBuildsMonitor#52]
Hi, I've updated to VS 2019.1 today and found out that IDE does not load the extension anymore. I've took a quick look at the documentation about this problem and found out that starting from 2019.1 version every extension must support asynchronous loading. Do you know about this problem, and if so, will the fix be available in the future? Your extension is great and it will be a huge loss to work on build times without it.

**Comment by KrzysztofBuchacz** [comment]
Thanks for reporting this issue, I'll take a look.

**Comment by KrzysztofBuchacz** [comment]
Fixed in v1.9
